sudo: false

language: python

services:
    - docker

jobs:
  include:
    - python: '3.8'
      env:
        - TOX_DOCKER_VERSION=v2.0.0a3
        - TOX_INI=tox.ini
    - python: '3.7'
      env:
        - TOX_DOCKER_VERSION=v2.0.0a3
        - TOX_INI=tox.ini
    - python: '3.6'
      env:
        - TOX_DOCKER_VERSION=v2.0.0a3
        - TOX_INI=tox.ini
    - python: '2.7' # tox_docker v2.0.0+ does not support Python2
      env:
        - TOX_DOCKER_VERSION=1.7.0
        - TOX_INI=tox-py2.ini

install: pip install tox-travis tox-docker==$TOX_DOCKER_VERSION

script: tox -c $TOX_INI -e flake8,basic,swaggerpetstore,httpbin
