name: Main workflow
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.rst'
jobs:
  python3:
    name: Test on Python 3
    runs-on: ${{ matrix.operating-system }}
    env:
      TOX_DOCKER_VERSION: 3.1.0
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install coverage tox tox-gh-actions tox-docker==$TOX_DOCKER_VERSION
    - run: tox -c tox.ini -e yapf,rstcheck,flake8,mypy,basic,swaggerpetstore,httpbin,asynchttpbin
    - run: coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
